### ISSUE TITLE
Webpack missing from Yarn lockfile

### ISSUE THREAD

**Issue by bvaughn** [somebee/dom-reconciler-bench#1]
Both the "build" and "watch" commands failed for me on a fresh install until I ran:
```sh
yarn add webpack webpack-cli -D
```

**Comment by somebee** [comment]
Thanks for reporting. I'd be very grateful if you look over the react version and improve potential slowdowns. The goal is to test actual raw reconciler performance, so shouldComponentUpdate is deliberately not used. Imba is not using its equivalent shouldRender, and vue is not using its built in reactivity either. It would be incredibly cool if it's possible to apply similar techniques to reconciliation in React.
